### PR TITLE
add configs for web embed mode

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Adds 3 new configs for the Web embed mode that were recently added to oCIS (see https://github.com/owncloud/ocis/pull/7670 and https://github.com/owncloud/ocis/pull/7766):

* `embed.enabled` Defines if embed mode is enabled.
* `embed.target` Defines how Web is being integrated when running in embed mode.
* `embed.messagesOrigin` Defines a URL under which Web can be integrated via iFrame.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

### CODE REVIEW

**Comment by dj4oC** [comment]
@JammingBen 
may I ask you to add a second section to the helm chart instead?
the current version would eigther deploy embedd mode or web - not both.

**Comment by JammingBen** [comment]
> @JammingBen may I ask you to add a second section to the helm chart instead? the current version would eigther deploy embedd mode or web - not both.

As far as I understood this PR only gives the ability to set this config, but it will default to empty (=not being set). I don't know much about helm charts though, maybe some of our experts can verify this?

If my assumption is correct it means Web will run in normal mode. The embed mode can then always be activated via the query param `mode=embed` (and optionally `embed-target=location`).

**Review by wkloucek — CHANGES_REQUESTED** [review]
I gave it a try after updating to oCIS 5.0.0-alpha.2 (because I heard on a different channel, that this version is needed).

When setting `services.web.config.mode` to `embed`, the regular oC Web that you can reach on whatever you have set in `externalDomain` will be replaced by the embeddable, stripped down oC Web. It looks like this:
image

In order to proceed with this PR we need to answer:
- should the chart always ship a full oC Web on the `externalDomain`? (I think it wouldn't make much sense to not ship a full oC Web!? Reasons welcome why it makes sense to only ship oC Web embed)
- there is a way to use oC Web embed

When it comes to the usage of oC Web embed, I have some questions:

1) https://owncloud.dev/clients/web/embed-mode/ is providing an example how to integrate oC Web embed:
`<iframe src="<web-url>?mode=embed"></iframe>`. 
Does that mean I can integrate a oC Web, that doesn't have the `WEB_OPTION_MODE` option set to `embed`?  This is also what I got from
   > The embed mode can then always be activated via the query param mode=embed (and optionally embed-target=location).

   Also appending `?mode=embed` results in a embed view in my tests. Maybe the question is: will this be supported until depreciated?

2) The oC Web embed seems to use /config.json as configuration. Is there documentation about whether a integrating application can overwrite some settings like e.g. `tokenStorageLocal` or providing access tokens instead of a OIDC login flow done by oC Web embed? Because if the config.json is the only mean of configuration, we might have a conflict between oC Web and oC Web embed or even multiple oC Web embed use cases (that can be solved by deployment in some cases).

**Comment by dj4oC** [comment]
> In order to proceed with this PR we need to answer:
> 
>     * should the chart always ship a full oC Web on the `externalDomain`? (I think it wouldn't make much sense to not ship a full oC Web!? Reasons welcome why it makes sense to only ship oC Web embed)
> 

YES please always ship Web.

**Comment by JammingBen** [comment]
Pushed again because the structure of the config changed a bit with https://github.com/owncloud/ocis/pull/7766.

**Review by wkloucek — APPROVED** [review]

**Pull request merged**
