### PR TITLE
Enhance office deployment

### PR DESCRIPTION
**Pull request by d7oc**
## Description
This PR enhances the office deployment. So that a postgres operator with pgbouncer is used to switch connections to the master

## Related Issue
None

## Motivation and Context
Better real world scenarios

## How Has This Been Tested?
Tested locally with k3d

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation generated (`make docs`) and committed
- [ ] Documentation ticket raised: <link>
- [ ] Documentation PR created: <link>

### CODE REVIEW

**Review by wkloucek — APPROVED** [review]
I successfully tested this on Minikube.

**Comment by wkloucek** [comment]
@d7oc can you please give it a look and merge once you're fine with the changes I did / you tested it?

**Comment by d7oc** [comment]
I thought we wouldn't go anymore with `pgbouncer` due to the issues in https://ownclouders.atlassian.net/browse/KOKO-1240?focusedCommentId=13296 ?

**Comment by wkloucek** [comment]
> I thought we wouldn't go anymore with `pgbouncer` due to the issues in https://ownclouders.atlassian.net/browse/KOKO-1240?focusedCommentId=13296 ?

We also already have it for the Keycloak deployment example.
https://github.com/owncloud/ocis-charts/blob/92e0ca68543c21ddf77b2e691186d224d1f01f54/deployments/external-user-management/helmfile.yaml#L8-L22

Please note that this is the ocis-chart repo. Therefore I see no problem using it here for demo purposes. For the record, this is the problem we're relating to: https://github.com/zalando/postgres-operator/issues/1928

**Pull request merged**
