### PR TITLE
add feature flag for external user management

### PR DESCRIPTION
**Pull request by wkloucek**
fixes https://github.com/owncloud/ocis-charts/issues/5
depends on https://github.com/owncloud/ocis/pull/4346

### CODE REVIEW

**Comment by PixelJonas** [comment]
If I see it correctly this "assumes" a specific configuration at the OIDC provider (e.g. there needs to be a client called `web` and it needs to be `public`).

When using this together with a keycloak instance (using `https://sso.mydomain.com/auth/realms/myrealm` and creating a client called `web` ) I get in a redirect loop with the following error being produced in the `auth-machine` 

```
auth-machine-5f86bcbb48-r92b7 auth-machine {"level":"debug","service":"auth-machine","pkg":"rgrpc","traceid":"00000000000000000000000000000000","client_id":"username:red.acted@gmail.com","time":"2022-08-01T10:11:55.76955884Z","message":"unknown client id"}
```
any idea how I could debug this?

**Comment by PixelJonas** [comment]
Ah ok, please reach out if can support testing this PR.

**Review by rhafer — APPROVED** [review]
Looks good to me. Needs to wait for ocis beta 6 being released though

**Comment by PixelJonas** [comment]
Is this at a point where I could test it with Keycloak? If I read [owncloud/ocis#4346](https://github.com/owncloud/ocis/pull/4346) this is only for client support on iOS/Android, right? Webbrowser should work?

**Comment by PixelJonas** [comment]
I wanted to test with upstream Keycloak but yeah. What do I need the LDAP server for?

**Comment by PixelJonas** [comment]
Ok, so if I want to add an external OIDC Server (Keycloak) I also have to run my own LDAP?
Can run the internal LDAP for the things oCIS is doing? I don't have an LDAP Server running at home and don't need one.

Is there any specific design decision, why oCIS does not use the [userinfo endpoint](https://connect2id.com/products/server/docs/api/userinfo)?

**Comment by PixelJonas** [comment]
ok, so when moving towards a home-based setup I prob. should move to the [k8s-at-home owncloud-ocis](https://github.com/k8s-at-home/charts/tree/master/charts/stable/owncloud-ocis) chart. AFAIK it starts the monolithic server.

Thank you very much. If I can support you in any way regarding OIDC integration or an operator based deployment, please reach out

**Pull request merged**
