### PR TITLE
enable renovate on stable branches, too

### PR DESCRIPTION
**Pull request by wkloucek**
## Description
enable renovate on stable branches, too

## How Has This Been Tested?
- `npx --yes --package renovate -- renovate-config-validator`:

```
 INFO: Validating renovate.json
 INFO: Config validated successfully
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation generated (`make docs`) and committed
- [ ] Documentation ticket raised: <link>
- [ ] Documentation PR created: <link>

### CODE REVIEW

**Review by nazliyanik — APPROVED** [review]

**Comment by wkloucek** [comment]
Argh... actually I intended to get PRs for new oCIS releases on the stable branches, too. But the current config will also create PRs for the Helmfiles. 

@d7oc what do you think about it?

**Comment by d7oc** [comment]
> But the current config will also create PRs for the Helmfiles.

I don't get this comment. What do you mean by PRs for Helmfiles? You mean all the stuff in the examples?

**Comment by wkloucek** [comment]
> You mean all the stuff in the examples?

Yes! as of now the examples on the `stable-` branches are just "frozen" / "unmainained". 

But same unfortunately applies to the `appVersion` (see eg. https://github.com/owncloud/ocis-charts/blob/12fb37837f0caba49990ff3d29845151e400a2cc/charts/ocis/Chart.yaml#L13-L14)

**Comment by d7oc** [comment]
I would not touch them. I would only offer up-to-date examples in the main branch. I would expect (haven't checked yet) that renovate also offers a way to exclude directories.

**Comment by wkloucek** [comment]
> I would only offer up-to-date examples in the main branch. I would expect (haven't checked yet) that renovate also offers a way to exclude directories.

There is `useBaseBranchConfig`, but then we'd need to change the renovate config on the `stable-` branches. 

I close this for now. Didn't anticipate that it needs that many changes.

**Pull request closed without merging**
