### PR TITLE
Add k3d to ci pipeline

### PR DESCRIPTION
**Pull request by xoxys**

### CODE REVIEW

**Comment by d7oc** [comment]
This PR adds a k3d deployment to the CI as requested in https://github.com/owncloud/ocis-charts/issues/3.

**Comment by wkloucek** [comment]
Nice!

I wonder if we could run a "kubectl -n <namespace> get pods" to see if there is actually something running? From https://drone.owncloud.com/owncloud/ocis-charts/1182/3/4 I can only see that Helm successfully handed some manifests to the Kubernetes API.

Maybe also a basic api resquest (eg. /app/list) would be nice to demonstrate how tests can interfere with this installation.

**Comment by d7oc** [comment]
> I wonder if we could run a "kubectl -n get pods" to see if there is actually something running? From https://drone.owncloud.com/owncloud/ocis-charts/1182/3/4 I can only see that Helm successfully handed some manifests to the Kubernetes API.

Added this now: https://drone.owncloud.com/owncloud/ocis-charts/1186/3/5

> Maybe also a basic api resquest (eg. /app/list) would be nice to demonstrate how tests can interfere with this installation.

Will try to add this too.

**Comment by wkloucek** [comment]
Nice
```
+ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS      AGE
kube-system   coredns-75fc8f8fff-c67vb                  1/1     Running   0             76s
kube-system   local-path-provisioner-5b5579c644-pxjcc   1/1     Running   0             76s
default       storagepubliclink-f4db5dfdb-dpqjj         1/1     Running   0             58s
default       settings-854cf75f5c-vrd87                 1/1     Running   0             62s
default       users-6bd669b6fd-v2k4m                    1/1     Running   0             62s
default       audit-cc8798488-rz7c6                     1/1     Running   0             62s
default       groups-57f56f8bf8-jq5fj                   1/1     Running   0             61s
default       appregistry-594f99bc79-6qrjf              1/1     Running   0             62s
default       webdav-57f9bf8599-jxdwr                   1/1     Running   0             58s
default       ocdav-bb866c6cf-wsgt5                     1/1     Running   0             61s
default       gateway-d748b4d-wgvbt                     1/1     Running   0             60s
default       frontend-848847956d-7gtth                 1/1     Running   0             60s
default       proxy-6bdbb64995-22r2t                    1/1     Running   0             60s
default       ocs-588c867fd9-vg4vw                      1/1     Running   0             60s
default       storageshares-56c846597b-64kzt            1/1     Running   0             59s
default       postprocessing-759b6d564-jg864            1/1     Running   0             62s
default       webfinger-6787cb56bf-jt2j9                1/1     Running   0             61s
default       idp-6666f585c9-st4dj                      1/1     Running   0             60s
default       authmachine-5dfd4f764c-gvmbw              1/1     Running   0             60s
default       storagesystem-75494d5d46-t4qvq            1/1     Running   0             62s
default       nats-55f49785c8-6pvvt                     1/1     Running   0             62s
default       web-5d8dcdfc4d-rc8kh                      1/1     Running   0             62s
default       storageusers-dc7cfd97d-r4zsg              1/1     Running   0             62s
default       eventhistory-6d7fbcddf5-28p5z             1/1     Running   0             62s
default       thumbnails-96b6c7595-j4546                1/1     Running   0             58s
default       idm-9c975cc5d-jt4mp                       1/1     Running   0             59s
default       store-69b756dc9b-kxw4c                    1/1     Running   0             59s
default       search-5886d4d5d6-vbb4b                   1/1     Running   0             59s
default       userlog-57cc986fbb-zdd9l                  1/1     Running   0             61s
default       graph-547b647699-q7gnf                    1/1     Running   0             61s
default       sharing-659dcdc96b-7zmw4                  1/1     Running   3 (37s ago)   59s
```

**Comment by d7oc** [comment]
For the record: We discussed internally about the curl check requirement and came to the conclusion, that we will add this with `helm test`. So there will be a new issue after this one to implement `helm test`.

**Review by wkloucek — APPROVED** [review]

**Comment by d7oc** [comment]
Follow up issue created as https://github.com/owncloud/ocis-charts/issues/423.

**Pull request merged**
