### PR TITLE
add web_token_storage_local option

### LINKED ISSUE #394: support `WEB_OPTION_TOKEN_STORAGE_LOCAL`
expose a configuration for `WEB_OPTION_TOKEN_STORAGE_LOCAL`

### PR DESCRIPTION
**Pull request by case0sh**
## Description
add a configuration for WEB_OPTION_TOKEN_STORAGE_LOCAL

# #Related Issue
- Fixes #394
- Blocked by https://github.com/owncloud/ocis/issues/7462 

## How Has This Been Tested?
- test environment: k8s, helm charts
- test case 1: try set to "false"

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation generated (`make docs`) and committed
- [ ] Documentation ticket raised: <link>
- [ ] Documentation PR created: <link>

### CODE REVIEW

**Review by wkloucek — CHANGES_REQUESTED** [review]
While this PR is fully functional and needs no changes, I currently propose to wait until https://github.com/owncloud/ocis/issues/7462 is fixed.

Therefore I'm blocking this PR until we know how to continue

**Comment by wkloucek** [comment]
Fix will come in https://github.com/owncloud/ocis/pull/7528

**Comment by micbar** [comment]
Backport to stable-4.0 and patch release?

**Comment by wkloucek** [comment]
> Backport to stable-4.0 and patch release?

Please see https://github.com/owncloud/enterprise/issues/6088#issuecomment-1757293731

**Review by wkloucek — APPROVED** [review]
I'm happy to merge after #437

**Pull request merged**
