### PR TITLE
add adoc values table

### PR DESCRIPTION
**Pull request by wkloucek**
fixes https://github.com/owncloud/ocis-charts/issues/67

### CODE REVIEW

**Comment by mmattel** [comment]
There is one issue with the adoc output...

If the source `values.yaml` files contains a link like it is currently used `[Secrets](#secrets)`, this link cant be rendered/resolved by Antora/Asciidoc. This style fo writing is typically for markdown. .adoc files need links to sections in the same page like: `xref:secrets[Secrets]` (see my issue where I noted that).

There are two possible mechanisms to resolve:
* Hard replacement of `[Secrets](#secrets)` --> `xref:secrets[Secrets]`
This impacts that the repos readme is not longer usable as the link is broken.
* Soft replacement - if we want to keep the repos readme - by using a go mechanism where you define based on the output format either the one or the other. One idea could be to define a variable that is being replaced dependent on the output format.

To be decided how to proceed

**Comment by mmattel** [comment]
Cool, but we are not finished 😅 

Knowing that this is some work, but this is needed to make these documents dynamic and includeable.

1. The naming of the `values-table.x.y` is not correct, this should be `values-desc-table.x.y` as it only contains the definitiona and description of the keys and not the yaml source.

2. Please create a file named `values-overwrite.yaml` which contains the yaml content of section minicube point 3. I will include that yaml file and you add this file into the README via templating.

3. Please autocreate a file named `values-adoc.yaml` based from values.yaml, no including in README.md necessary, but a replacement of ref:... to xref:... in the same way as you did for `values-desc-table.x.y`. I will include that file and with proper xrefs it will point to the correct secrets heading. Maybe to add a comment on top that it is autogenerated based on values.yaml.

4. Please create following files which replace the embedded content in README.md via templating: `security.yaml`, `email.yaml` and `example-nginx.yaml` which are in section Secrets and Example with NGINX

**Review by mmattel — CHANGES_REQUESTED** [review]
Changes needed, see: https://github.com/owncloud/ocis-charts/pull/68#issuecomment-1202359174

**Review by dragonchaser — APPROVED** [review]

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
GREAT 👍

**Pull request merged**
